import Navbar from '@components/Navbar/Navbar';
import Footer from '@components/Footer/Footer';
import './globals.css';

export const metadata = {
  title: 'TEDxNTUA 2025',
  description:
    'Generated by TEDxNTUA2025-IT, tedxntua 2025, TEDX NTUA 2025, TEDxNTUA 2025, TEDxNTUA',
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: './favicons/favicon-32x32.png'
    },
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '16x16',
      url: './favicons/favicon-16x16.png'
    }
  ]
};

export default function RootLayout({children}) {
  return (
    <html lang="en" className="dark">
      <body>
        <Navbar />
        <main className="max-w-[2000px] mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
